### ISSUE TITLE
Discuss Google Analytics replacements

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#100]
## To do

We will look into the replacements and suggest accordingly

## Requirements

What are the exact requirements for the analytics?

**Comment by jhenshall** [comment]
As discussed on the call, this will not be used so proactively but some requirements that would be nice to have:

1. Numbers of visits to site
2. Number of views for each page
3. Referrer - i.e. if the user has come directly from another website - URL of referring page

These have helped in the past for investigating sudden spikes of traffic - where they come from and what they see on the site. Can be good to know overall numbers to understand scale of site. Can also be used to shape future changes but has not been used much until now.

**Comment by kopitek8** [comment]
Here is the tool we talked about in the meeting: https://posthog.com/blog/best-gdpr-compliant-analytics-tools

**Comment by Katbaloo** [comment]
@jhenshall to review and revert back with thoughts, questions, and/or green light to move forward.

**Comment by Katbaloo** [comment]
Let's go ahead and move forward with posthog.  

We do want to note that it remains unclear what counts as an "event" so if 1 million events per month ends up being too little we will need to revisit or shift to an alternataive solution.

**Comment by kopitek8** [comment]
Linking another related issue here: #75
