### ISSUE TITLE
[Illustration] Home > Banner rough sketches and ideas

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#101]
## Rough sketches

![Image](https://github.com/mapswipe/community-website/assets/25280806/d998af19-1e5a-4084-8d5c-b077de2baf7d)

![Image](https://github.com/mapswipe/community-website/assets/25280806/8dda2c2c-399e-413d-8815-38b75643bf59)

![Image](https://github.com/mapswipe/community-website/assets/25280806/de4ea46e-4b48-405b-831c-753afe5318eb)

## To do

Finalize one illustration so we can move forward with it

**Comment by Katbaloo** [comment]
Agree with your team that the third option (large phone + small person) is our favorite and like the idea of a simple animation that would rotate different types of landscape on the phone.

**Comment by kopitek8** [comment]
We're confirming the third option (large phone + small person) as per multiple feedback from multiple people
