### ISSUE TITLE
[Illustration] Get Involved > Banner

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#102]
![Image](https://github.com/mapswipe/community-website/assets/25280806/8d95c65a-8434-44bd-b7eb-db812b06dd2c)

**Comment by Katbaloo** [comment]
If this is the banner illustration can we consider how to incorporate all the ways that are reflected in how to get involved (ie. phone, laptop, group event, whatevere we land on for organziations).  At a glance, the takeaway with this option is that you get involved on your laptop.

**Comment by kopitek8** [comment]
We have come up with another rough sketch incorporating the feedback you gave, @Katbaloo. Please have a look at it. Attaching below.



![Image](https://github.com/mapswipe/community-website/assets/25280806/6d9119b7-36b5-4761-a529-e5dda192fdc7)

**Comment by Katbaloo** [comment]
this will work!

**Comment by kopitek8** [comment]
Great. We will move forward with this sketch.
