### ISSUE TITLE
[Illustration] Get Involved > Individual

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#103]
![Image](https://github.com/mapswipe/community-website/assets/25280806/88182ce2-fcba-4f62-8139-cd0d91d89c68)

![Image](https://github.com/mapswipe/community-website/assets/25280806/ba4c2bb8-cd16-4923-921a-9fcc49752419)

**Comment by Katbaloo** [comment]
main feedback on these two options is that they both seem to convey a phone call or a video call, which is not something related to MapSwipe activity or the individual involvement.  wondering if there is a direction to take this that is more reflective of the actual engagement type (phone, laptop)?
