### ISSUE TITLE
[Illustration] Get Involved > Organization

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#104]
![Image](https://github.com/mapswipe/community-website/assets/25280806/1af2f55e-00e3-4de6-826e-d5bde8d7cfa0)

**Comment by Katbaloo** [comment]
As discussed on call, this one feels a little too "corporate" and "business park" to represent non-profits, humanitarian orgs, academic etc.

**Comment by Katbaloo** [comment]
Also want to flag that in reviewing the illustrations for the Get Involved section, we seem to be missing one for Group?


![Image](https://github.com/mapswipe/community-website/assets/109613542/ab90d66e-f05b-4eb8-911f-1f4cf94448b3)

**Comment by kopitek8** [comment]
@Katbaloo We are planning to use the same illustration you see in Figma for 'Group'. What are you thoughts on this, Kat?

**Comment by kopitek8** [comment]
As for the illustration for the organization section, we'll come up with other draft and let you know.

**Comment by Katbaloo** [comment]
@kopitek8 regarding the 'Group' image, we have looked at the figma and do not see a group image?  Unless you are talking about the placeholder one?  can you clarify?  also, perhap we should open a separate issue for this image to keep it separate from the 'organization' image review?

**Comment by kopitek8** [comment]
@Katbaloo Yes. Basically, we are going to create a better version of the placeholder illustration. Created a new issue for it #109

**Comment by kopitek8** [comment]
@Katbaloo As for the organization illustration, we are thinking of replacing the big buildings with small houses that look more like a non-profit organizations' headquarter/office. How does that sound?

**Comment by Katbaloo** [comment]
looking at the figma, if the below illustration is what we are considering for organization (even though it is labelled corporate), then it is better then the business park sketch from before.  **However,** the general style of this one doesn't seem to align with the other three iluustrations on this page. 

![image](https://github.com/mapswipe/community-website/assets/109613542/e34678ae-f25c-47f2-a85a-60eddd8ec223)

**Comment by kopitek8** [comment]
Thanks for the feedback, @Katbaloo. We are working on making this more consistent with the other illustrations you see in the screen as well.

**Comment by kopitek8** [comment]
UPDATE: 

![Image](https://github.com/mapswipe/community-website/assets/25280806/fba61382-8f59-46ff-9a96-f91b7fc04900)
