### ISSUE TITLE
[Illustration] Get Involved > Donate

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#105]
![Image](https://github.com/mapswipe/community-website/assets/25280806/3edf3cc1-0592-4374-89fa-5b0e207335fe)

**Comment by Katbaloo** [comment]
as discussed on call, this could work, but curious if there is an creative way to convey what the $$ donated allows us to do, support, etc.

**Comment by kopitek8** [comment]
@Katbaloo What we are thinking: the content next to the illustration will help convey the message about what the donated amount allows MapSwipe to do.

**Comment by Katbaloo** [comment]
sounds good. of the options in the Figma we prefer the hand/heart version 


![Image](https://github.com/mapswipe/community-website/assets/109613542/79c3d6b9-5928-4a01-a419-eff3a237c01d)
