### ISSUE TITLE
Proposed edits/feedback on Data & Project Detail pages

### ISSUE THREAD

**Issue by Katbaloo** [mapswipe/website#110]
To discuss on Monday Jun 19 call:

Now that we are seeing the **Data** and **Project Detail page** in Figma UI we have been able to do some critical thinking about what these pages need to have and what make the most sense for how visitors would be guided to engage with it.  Some key realizations that have surfaced are captured below.  In addition, we have done some informal examples where relevant to better illustration our thinking.

We are mindful that our timeline is ticking down and we will need to hear from your team on what, if any, impact on that timeline may be at risk.  It would be helpful to get that clarity from your side so that we can better determine the impact and if we have any flexiblity, given the importance of these pages, to allow for that timeline adjustment.

**Key feedback on these two pages:**

- Data Page: Top section currently has too much real estate for what is there.  We can get rid of the '# of groups' stat as this isn't really meaningful to those landing on this page and we wonder if we can explore something other than square or rectangular box to display the remaining 2 stats? ([see example](https://www.figma.com/file/lrh1moXmEwgbRBUL1bmrVV/MapSwipe-website---suggestions?type=design&node-id=18%3A32&t=9ca1eA4FWzyTQnOR-1))

- Explore the Data section:  ([see example](https://www.figma.com/file/lrh1moXmEwgbRBUL1bmrVV/MapSwipe-website---suggestions?type=design&node-id=18%3A32&t=9ca1eA4FWzyTQnOR-1))
--We need to make the search filter options more prominent and de-emphasize the map.  We've come to clarify that the purpose here is to explore the data. not necessarily explore the map.
--Project cards below the map: looking to have these reworked on how they pull the available fields to better break up topic, region, org, and project type and use more icons v. text for fields being displayed

- Project Detail Page: similar to Data page project cards, we are interested to pull in more individual fields w/icons and the project image at top of page. ([see example](https://www.figma.com/file/lrh1moXmEwgbRBUL1bmrVV/MapSwipe-website---suggestions?type=design&node-id=18%3A32&t=9ca1eA4FWzyTQnOR-1))

**Comment by jhenshall** [comment]
I have added the example links that all go to the same [Figma mockup](https://www.figma.com/file/lrh1moXmEwgbRBUL1bmrVV/MapSwipe-website---suggestions?type=design&node-id=18%3A32&t=9ca1eA4FWzyTQnOR-1). Some of this is very rough with comments to explain some ideas. This is our thinking but not intended to be the final design. Good to get your thoughts and feedback.

**Comment by kopitek8** [comment]
Laying down the artefacts that could help us better discuss the designs below.

## Initial Observation

- Data > Explore Map
	- Organization filter might not work or be available in the API response
	- Date from and to might not work because as per our initial findings, the API gives only one date
- Data > Project Cards
	- Is HOT an organization?
	- We suggest showing area mapped as well
	- Images might not be there for all projects
- Project Detail
	- Country might not be available for each project  
	- Other small details (date, project type) are dependent on the Data page's Project Cards section

## Project API Response

```
{
        "type": "Feature",
        "properties":
        {
            "idx": 735.0,
            "project_id": "-Mj47Mk-DGY40GoArSqe",
            "name": "Disaster Risk Reduction - Togo (4) German Red Cross",
            "project_details": "Togo has increasingly been affected by extreme weather conditions that have become unpredictable. The German Red Cross is cooperating with the Togolese Red Cross in the areas of disaster risk reduction and climate change adaptation. This includes a risk analysis in the communities for which up-to date mapping is required. ",
            "look_for": "Buildings",
            "project_type": 1.0,
            "tile_server_names": "{maxar_standard}",
            "status": "finished",
            "area_sqkm": 1270.5740564583357,
            "centroid": "POINT(0.584166021363725 10.59212216892331)",
            "progress": 1.0,
            "number_of_users": 168.0,
            "number_of_results": 293124.0,
            "number_of_results_progress": 232392.0,
            "day": "2021-09-20 00:00:00"
        },
        "geometry":
        {
            "type": "Point",
            "coordinates": [0.584166021363725, 10.59212216892331]
        }
    },
```
