### ISSUE TITLE
Overall - Footer links to be used throughout the website

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#121]
## Required Links

We require links for the footer section (as listed below):

- Facebook
- Twitter
- Instagram
- GitHub
- Email

**Comment by Katbaloo** [comment]
links provided below.  We would like to add a link to the OSM MapSwipe wiki page as well.
@jhenshall is there a standard icon to use to link to the OSM wiki??

Facebook: https://www.facebook.com/TheMissingMaps
Twitter: https://twitter.com/mapswipe
Instagram: https://www.instagram.com/themissingmaps/
GitHub: https://github.com/mapswipe
OSM MapSwipe Wiki: https://wiki.openstreetmap.org/wiki/MapSwipe
Email: info@mapswipe.org

**Comment by kopitek8** [comment]
@jhenshall Could you please confirm if you will be providing the logo or should we go with what we think suits best?

**Comment by jhenshall** [comment]
No real preference on this @kopitek8 @Katbaloo, if you have one that you think suits, go for it?! I was initially thinking just a simplified OSM logo, but notice that Missing Maps uses a newspaper icon.

**Comment by kopitek8** [comment]
Thanks for confirming, @jhenshall. We'll go with a suitable icon for this

**Comment by kopitek8** [comment]
@jhenshall We found this logo in the OSM website. Could you confirm it we can use it?

Link to the website: https://wiki.openstreetmap.org/wiki/Logos
Link to the SVG logo: https://wiki.openstreetmap.org/w/images/7/79/Public-images-osm_logo.svg

**Comment by danbjoseph** [comment]
for the footer? i think the link to the OSM wiki should also be a single color icon to match the others.
<img width="464" alt="Screenshot 2023-06-21 at 9 56 16 AM" src="https://github.com/mapswipe/community-website/assets/4806884/c934b0fd-8b98-46a5-b729-1b498f288c41">
as mentioned by Johnny, here's what the Missing Maps website uses:
<img width="285" alt="Screenshot 2023-06-21 at 9 58 02 AM" src="https://github.com/mapswipe/community-website/assets/4806884/3ee16e54-9318-4642-b3da-a134241a2094">

**Comment by Katbaloo** [comment]
@kopitek8, I see that in latest changes to staging server we have the magnifying glass for the wiki icon.  Can we change it to mirror the newspaper icon that [Missing Maps](https://www.missingmaps.org/) is using?

**Comment by kopitek8** [comment]
Thanks for letting us know, @danbjoseph @Katbaloo
