### ISSUE TITLE
Create 3 articles for 'News & updates' section

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#139]
## To do

Please go through this guide and send us 3 articles for the 'News & updates' section to add in the website: https://github.com/mapswipe/community-website#adding-news--updates-or-blogs

**Comment by jhenshall** [comment]
[MapSwipe_blogs.zip](https://github.com/mapswipe/community-website/files/11907117/MapSwipe_blogs.zip)

@kopitek8 - blog files and images in attached zip. I was going to add myself but don't want to interfere, so will wait until we have gone through the workflow.

@Katbaloo @danbjoseph - I wasn't certain if we decided to link to existing blogs (MM, ARC) or totally duplicate content. I have just done a summary and a link to existing blog for now to have something done for homepage. Can change later if needed. Cheers!

**Comment by kopitek8** [comment]
Hey @jhenshall 

Could you recheck the Madagascar .md file. I think you forgot to rename the author:

![image](https://github.com/mapswipe/community-website/assets/25280806/abc2332d-2d16-41a2-8aaf-48980c57acfd)

**Comment by jhenshall** [comment]
> Could you recheck the Madagascar .md file. I think you forgot to rename the author:

Hey @kopitek8 - that is correct author. Laurie was previously part of the MapSwipe team whilst working with MSF.
