### ISSUE TITLE
Results not available for download

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/website#140]
Some projects on the new site do not have the results datasets available for download: `Aggregated Results` and `Aggregated Results (with Geometry)`

- Example where results available on [old site](https://mapswipe.org/en/project.html?projectId=-Mx4ZBDpEJpOycbt8ZcD) but not [new site](https://mapswipe.togglecorp.com/en/projects/-Mx4ZBDpEJpOycbt8ZcD)
- Example where results are available on both the [old site](https://mapswipe.org/en/project.html?projectId=-MYHTLBsTDVZEBmWq8-l) and [new site](https://mapswipe.togglecorp.com/en/projects/-MYHTLBsTDVZEBmWq8-l)

@AdityaKhatri @kopitek8

**Comment by thenav56** [comment]
Hey @jhenshall For the current deployment, we are using a mock endpoint that doesn't consist of all of the data from production.
After we deploy the changes from https://github.com/mapswipe/python-mapswipe-workers/pull/859 to production we can then switch to production endpoint. Then all the data should exist. We will validate and close this ticket after the deployment.

Mock Endpoint Used: https://api-mock-mapswipe.dev.togglecorp.com/api/

**Comment by jhenshall** [comment]
Ah perfect, that makes sense. Yes, At least we have some examples to test once pointing at prod endpoint. Thanks @thenav56 !

**Comment by kopitek8** [comment]
Just to be perfectly sure, we'll make a note of this to test it out after production deployment @jhenshall 

Closing the issue with a comment for now
