### ISSUE TITLE
Make a copy of at least 3 projects in the existing website to check after production

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#143]

**Comment by kopitek8** [comment]
For the projects: https://github.com/mapswipe/community-website/issues/140

**Comment by kopitek8** [comment]
## Project IDs

1. -MYHTgEvhIenEhWwOomC
2. -Mx4ZBDpEJpOycbt8ZcD
3. -MywlVCY9-95B-4B5PwI

**Comment by kopitek8** [comment]
## What to do?  
- Make sure that all the static downloadable files are present in the projects

## How to do?  
- Three sample project IDs from the existing MapSwipe Website will be taken  
	- -MYHTgEvhIenEhWwOomC  
	- -Mx4ZBDpEJpOycbt8ZcD  
	- -MywlVCY9-95B-4B5PwI  
- All their static download files will be downloaded and inspected (for size)  
- The downloaded files will be kept in a separate folder to tally side by side later on  
- Some of the content will be randomly inspected

## Projects x Dataset Availability Table (previous website)

S.N. | Dataset Name | Data Type | -MYHTgEvhIenEhWwOomC | -Mx4ZBDpEJpOycbt8ZcD | -MywlVCY9-95B-4B5PwI
-- | -- | -- | -- | -- | --
1 | Aggregated Results | CSV | Yes | Yes | Yes
2 | Aggregated Results (with Geometry) | GeoJSON | Yes | Yes | Yes
3 | HOT Tasking Manager Geometries | GeoJSON | Yes | Yes | Yes
4 | Moderate to High Aggrement Yes Maybe Geometries | GeoJSON | Yes | Yes | Yes
5 | Groups | CSV | Yes | Yes | Yes
6 | History | CSV | Yes | Yes | Yes
7 | Results | CSV | Yes | Yes | Yes
8 | Tasks | CSV | Yes | Yes | Yes
9 | Users | CSV | Yes | Yes | Yes
10 | Area of Interest | CSV | Yes | Yes | Yes

## Next Steps (new website)

- Make sure the datasets are available in the website and downloadable as mentioned in the table above
- Tally the downloaded files against locally stored files in project ID folders (eg: folder name "-MYHTgEvhIenEhWwOomC" has all downloaded content)

**Comment by kopitek8** [comment]
The latest deployed website has all exact data as the previous website

**Comment by kopitek8** [comment]
@jhenshall All the data are present exactly as they were in the previous version of the website. This GitHub issue was created to make sure that the data does not get lost and it's all there. Reiterating the main issue that gave birth to this: #140

**Comment by jhenshall** [comment]
Amazing! Thanks for being on top of this and double checking @kopitek8
