### ISSUE TITLE
Check if texts in the website can be changed through Transifex

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#168]

**Comment by kopitek8** [comment]
**UPDATE**

We can update the main English texts through Transifex but it is a paid feature. As MapSwipe is an open-source and nonprofit organization, Transifex might upgrade the account to premium. Please communicate with the Transifex support team and update us.

@danbjoseph

**Comment by danbjoseph** [comment]
Where are the files in the repository? And what is the process for using the Transifex CLI to push the updates to the central language up to the project on Transifex?

**Comment by tnagorra** [comment]
The translations are inside https://github.com/mapswipe/website/tree/main/public/locales

We have setup a Github integration in Transifex. Whenever we push the updated translations for english in the `main` branch, the translations are synced to Transifex.

**Comment by jhenshall** [comment]
I spoke to Transifex. We are already on the [open source tier](https://help.transifex.com/en/articles/6236788-open-source-projects) - which gets us the basic plan for free. There is no way to get premium features without significant cost.

I see @danbjoseph made the text change yesterday. That is how we did it on the old site. I guess this is the way forward, just needs documenting (which you might already be on?).

**Comment by jhenshall** [comment]
Ok Transifex have followed up and said they'd be willing to give us the Premium features for free if we add their logo to the website as a partner.

I think this would have to be agreed by the governance team but it would be good to understand technically if this is needed. Perhaps editing directly on Github is good enough with sufficient documentation?

cc. @danbjoseph @Katbaloo @kopitek8

**Comment by danbjoseph** [comment]
i've started a convo with the rest of the governance team in slack and will post the outcome of our discussion here.

**Comment by danbjoseph** [comment]
editing on GitHub is fine
