### ISSUE TITLE
Transifex documentation

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#169]
## The Idea

- A tutorial guide or document with the following
  - [x] How to add strings via Transifex
  - [x] How to add new languages in the dropdown of the website
  - [x] How to get the latest in the website

**Comment by kopitek8** [comment]
## Edit Source Strings
- Pull the latest changes from the `main` branch  
- Checkout to a new branch  
- Navigate to the source string files [here](https://github.com/mapswipe/website/tree/main/public/locales/en)  
- Open appropriate file(s) and edit string(s) as per requirement  
- Push the changes to the local branch  
- Create a pull request to the main branch  

## Translate Strings
### As Translator
- Go to Transifex project  
- Click on the language you are looking to translate the source into  
- Open the file to translate the string  
- Translate individual string and save changes  

### As Reviewer
- Open individual strings, make sure they are correct, and click the 'Review' button  
- Continue translating and reviewing the strings until all the strings are translated and approved  
- **_NOTE: Reviewers must have appropriate permission_**

## Update The Website
- After all the strings are 100% translated in Transifex, a pull request will be sent to the main branch  
- Merging the pull request will trigger a latest build and the same will be deployed in production
- **IF LANGUAGE IS NOT PRESENT IN THE WEBSITE**
- Add the supported language as per the [supported languages](https://github.com/mapswipe/website#supported-languages) guide

**Comment by kopitek8** [comment]
@jhenshall Do you think the guide (latest comment) is enough to get started?

**Comment by jhenshall** [comment]
Hey @kopitek8 - yes, this is great thanks!

@Katbaloo and I will be going through things in detail later today and attempt to make some changes to the website. I think great if you can publish these so we have all the instructions in one place. If we see anything that needs changing, we can create a pull request, to run by you first?

**Comment by kopitek8** [comment]
@jhenshall Great. We will merge the guide in the READ ME file itself so that everything is consolidated. If there's anything that needs changing, you can either create a PR or ask us to do it as you mentioned.
