### ISSUE TITLE
Add preview screens in the website for sharing

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#171]
## The Idea

- Have a small preview screen while sharing the website over WhatsApp
- It can be either for a whole website or for specific website pages. @jhenshall to confirm and share the following information:
    - Title
    - Description
    - Image

**Comment by Katbaloo** [comment]
@kopitek8,
@jhenshall & I have discussed and can confirm the below for use for whole website:

**- Title:** MapSwipe
**- Description:** Volunteer from your phone. Make a difference worldwide.
**- Image:** use the blue MapSwipe logo
https://drive.google.com/file/d/0B8W6rNfDtpJ4VjB0YWotLWJadTQ/view?usp=drive_link&resourcekey=0-9IbYi1X7Tlz3-shhQNGp5g
