### ISSUE TITLE
Add Hungarian language in the website

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#175]
Action items for the task

- [x] Development work
- [x] Review by Hungarian team reviewer
- [x] Merge the PR (sent by Transifex after strings are 100% reviewed)

**Comment by danbjoseph** [comment]
There is one Reviewer on the Hungarian team on MapSwipe Transifex. I sent them a message asking if they could please review.

**Comment by kopitek8** [comment]
Development work is complete so removed the `dev` tag. Since we are awaiting the reviewer to review the strings, added the `comms` and `content` tag.

**Comment by danbjoseph** [comment]
I received this response back:
> I would suggest to skip an official review because it freezes the translations and it can be difficult to modify them later. It may happen that you spot an error just months or even years later and if the translation is reviewed it is cumbersome to make it writeable again. (For example for small entries it is not always clear what kind of suffix or ending should be there for a Hungarian word or I am now considering to transform the website texts from a more polite style to a more informal one as it is already for the app.)
> I had been a professional translator for about a decade at the European Commission so I can assure you that my translations are of high quality but I would propose to use the in this unreviewed form (and re-generate the e.g. once a year to incorporate potential modifications).

@jhenshall @Katbaloo and TC team - what are your thoughts on modifying the automated workflow accordingly? That is, to use translated strings and not require them to be additionally all marked as reviewed.

**Comment by kopitek8** [comment]
@danbjoseph @jhenshall @Katbaloo Should we proceed with the workflow of not requiring 100% review for the whole project?

**Comment by jhenshall** [comment]
What a great comprehensive reply. I'm pretty sure that is how the app works anyway with no official reviewers, so agreed - let's go with no review needed.

As a side note, maybe it's worth a disclaimer in the footer saying that we cannot confirm the accuracy of all translations and a link to Transifex for anyone that notices a mistake?

**Comment by danbjoseph** [comment]
@kopitek8 is there a way to configure per language whether to require the review step? for example, for widely used languages with lots of translators and reviewers we might want the review step but for a language with just a couple of translators we might want just the single step of translating (no review).

**Comment by kopitek8** [comment]
@danbjoseph No. We cannot set workflow per language. The Transifex integration with GitHub only allows us to configure this option (review step) for the whole project. 

You can check this official Transifex document about the integration: https://help.transifex.com/en/articles/6265125-github-installation-and-configuration#h_de29ef5cec

**Comment by danbjoseph** [comment]
i think we can change it to 100% translated and content grouping of PRs to be "All resources and languages"

**Comment by tnagorra** [comment]
We have updated the GitHub integration with the above instructions.

**Comment by kopitek8** [comment]
@danbjoseph Could you please check this PR and make sure that everything is working as expected: https://github.com/mapswipe/website/pull/189

From our understanding, a PR is created (or a commit committed) as soon as a single resource is 100% translated. In the scenario I mentioned, you can find a Czech file committed (privacy.json).
