### ISSUE TITLE
Website - Data page - project date formats

### ISSUE THREAD

**Issue by Katbaloo** [mapswipe/website#186]
I seem to recall that the plan for how dates display was that they would be informed by the user's browser settings?  If that is the case, then it may not working properly as we have folks in DD/MM/YYYY regions seeing MM/DD/YYY formats. 

1. can we check/fix this? 
2. if the browser solution doesn't work then can we default to the more universal DD/MM/YYYY format?

![image](https://github.com/mapswipe/website/assets/109613542/335e31b2-cb48-4bda-9799-159e209d140e)

**Comment by kopitek8** [comment]
Yes, @Katbaloo. The plan was to display the date as per the user's browser settings. We will look into the issue and update you.
