### ISSUE TITLE
Develop Data page

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#32]
## User Story

As a user, I want to click on the ‘Data’ page so that I can see:

- Statics
  - Total number of contributors
  - Total number of swipes
  - Total groups
  - Kilometers swiped
- Project/mission type context
- Map with filters
- A table of all the MapSwipe projects
- A view of downloadable MapSwipe data

**Comment by Shhhhhubh** [comment]
## Updated User Stories 
As a user, I want to click on the ‘Data’ page so that I can see:
Statics
 - Total number of contributors
 - Total number of swipes
 - Project type context
 - Map filters
 - Map
 - Card view of all the projects
 - Downloadable MapSwipe data
