### ISSUE TITLE
Confirm the content for 'Recent News & Update'

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#61]
## Questions

1. How many news and update will there be on the home page? (Suggestion: 3)
2. Will the news and update be static or dynamic?

**Comment by kopitek8** [comment]
Hey @jhenshall @Katbaloo 

What do you guys think about this section?

**Comment by Katbaloo** [comment]
1. We agree with 3 on the home page
2. we are not sure what is possible.  ideally, these posts would be pulled from where they already live online (Missing Maps blog, Medium, etc.). We would like to be able to put in the source URL and it would pull the image, headline, date, & blurb.  Would be great to be able to edit those if they display weird, but not sure if that's possible?

**Comment by tnagorra** [comment]
Is the "blogs" section different form the "recent news and updates" section?
We were planning to add feature to create blog inside mapswipe website using markdown.
Related to https://github.com/mapswipe/community-website/issues/86

**Comment by kopitek8** [comment]
As per the latest conversation, 'Blogs' and 'News & updates' are tied up
