### ISSUE TITLE
Confirm what happens when we click on the buttons on the Get Involved page

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#66]
## Requirement

Links and reference point to where the various links in the Get Involved page lead to. For example, where does the "Volunteer: tech support" button lead to?

## Example Screenshot

![Image](https://github.com/mapswipe/community-website/assets/25280806/47d7ee54-299e-46f2-bfdc-794c2cf0dfce)

**Comment by Katbaloo** [comment]
Get involved links:

Download the app:  app store links
Volunteer tech support: https://github.com/mapswipe/
Volunteer translation: transifex page
Download tooklit button: link to a google folder (URL to come)
Submit query (for corporates): link to a google form (URL to come)
Tell us more (for orgs): link to a google form (URL to come)
Donate now: https://opencollective.com/mapswipe

**Comment by Katbaloo** [comment]
Updating to include all links:

Get involved links:

Download the app: app store links
Volunteer tech support: https://github.com/mapswipe/
Volunteer translation: transifex page
Download tooklit button: https://drive.google.com/drive/folders/1j5XnyqI_LKYBCg9oJaaWIKbsBxwB8Cld?usp=drive_link
Submit query (for corporates):https://docs.google.com/forms/d/e/1FAIpQLSf_05ZvC4i7HfDgYqedvsPxG66o8SHMaKs1GpnLC9KVFa4FuQ/viewform?usp=sf_link
Tell us more (for orgs): https://docs.google.com/forms/d/e/1FAIpQLSetcSda6EyuvOXMUPe7Gw7wNNIdR9R9RlvOi1j9Zu-C3ZXtbg/viewform?usp=sf_link
Donate now: https://opencollective.com/mapswipe
