### ISSUE TITLE
Confirm the content for Privacy and Cookies page

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#75]
## Question

Are the content for the two pages the same as before?

**Comment by jhenshall** [comment]
Privacy page - please keep the existing content
Cookie page - the only cookie we currently mention is Google Analytics. But we are removing this from the site? Can you advise if any other non-functional cookies will be used? If not, perhaps we don't even need a cookie page

**Comment by tnagorra** [comment]
If we are removing Google Analytics, we do not have any other cookies.

We can also consider some other analytics tool that is GDPR compliant.
Eg: https://posthog.com/blog/best-gdpr-compliant-analytics-tools#3-umami

**Comment by jhenshall** [comment]
Thanks @tnagorra! Never seen that before and could be ideal to have some more privacy-focussed, basic tracking on the site. We did have instances before where we'd have a sudden spike in users, and it was good to be able to see this and where the traffic came from.

Will it be much work to add it? Will need to confirm with @Katbaloo.

**Comment by kopitek8** [comment]
@jhenshall Any update on the Cookies page's content?

**Comment by jhenshall** [comment]
@kopitek8 - we need confirmation on the use of analytics #100 - and whether these will use cookies. If not, then confirmed by @tnagorra that no other cookies used, so we can remove page entirely.

Note: if we remove the page, we will also have to remove the follow text from the Privacy page:

> If you use our website, we may also obtain information about your visit to our website by using cookies. Please visit our [cookie policy](https://mapswipe.org/en/cookies.html) for information on this.
