### ISSUE TITLE
Figure out the project status to be displayed in the website

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#84]
## What's There Currently

Currently, there are about 8 or more project statuses in the website's Data page. Some of the statuses are: active, inactive, finished, private_finished, archived

## What's To Be Included

We need to figure out how many project statuses we are to display in the website. 

## The Plan

Currently, there is no mechanism to filter project list by status. So, we are planning to add a filter by project status filter in the Data page to make it more convenient to the users. For that, we need to figure out which statuses we are to include

**Comment by Katbaloo** [comment]
Just include Active and Finished in the website data page filter options

**Comment by tnagorra** [comment]
@Katbaloo So, the mapswipe website will only list projects that are active or finished?

**Comment by kopitek8** [comment]
@jhenshall and @Katbaloo to finalize it
