### ISSUE TITLE
Confirm which data points are to be plotted in the map

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#85]
## What's There Currently

Currently, there are 3 project statuses in the map: active, inactive, and finished. And, we show the data points for these three status in the map at the moment. Screenshot below.

![Image](https://github.com/mapswipe/community-website/assets/25280806/4fac0814-2284-4155-9741-2c53c213ae20)

## What's Will Be There

Do we also show all the projects (apart from active, inactive, and finished) in the map?

**Comment by jhenshall** [comment]
As mentioned comment on #84 - please only show active and finished on the map. Remove inactive and don't show any others. Thanks.
