### ISSUE TITLE
News and updates section redirect out of website or within website?

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#86]
## Question

What's the idea behind the 'News & updates' section? As of now and as per the content document, the updates mentioned in the section are to be redirected out of the website. Is that the case or are we going to create some sort of a 'Blog' section and integrate it within the website?

**Comment by Katbaloo** [comment]
Redirecting is the expected usual case.  However, if we are able to have the option of crafting & posting something directly then it could be good have. Let us know if that's an option.

**Comment by Katbaloo** [comment]
@kopitek8 
Reposted from Slack channel:

- Dan has raised some valid issues with our plan to pull external links v. manually add an article direct to our site with appropriate attribution (ie. Originally posted on Missing Maps blog).  

- Is it possible to revisit this to make the news and updates section just be manually created by us every time and not do any auto pull from a external source? This would make the process for adding a news/update external article the same as if we were posting an original blog to the site.
