### ISSUE TITLE
Confirm data to be exported

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#88]
## Context

Dan and Benni are to finalize what data are to be exported in the Project Detail page. Previously, Dan shared this Google Sheet: https://docs.google.com/spreadsheets/d/1uM9hCqFHwNlRK8lb7t2D3s0cosLrOKUEAMLkseaJ21s/edit#gid=0

## To do

Dan and Benni to finalize which data are to be exported.

## Link to Slack message
https://mapswipe.slack.com/archives/C055AGY53AQ/p1684856622522919

**Comment by danbjoseph** [comment]
spreadsheet mostly updated

**Comment by tnagorra** [comment]
We have updated the html generation so that only link that are available are seen on the website.
Does that work @danbjoseph ?

**Comment by danbjoseph** [comment]
sounds right to me!

**Comment by kopitek8** [comment]
Great. We will proceed with logic, @danbjoseph. 

Closing this issue now that we have what we need here.
