### ISSUE TITLE
General - Confirm and finalize the styles in moodboard

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#93]
## Moodboard

![Image](https://github.com/mapswipe/community-website/assets/25280806/991c33e8-4509-4d35-bc9d-385e71313d21)

## To do

Confirm the colors, design, and icons on the moodboard

**Comment by Katbaloo** [comment]
Confirming the following style options:

![Image](https://github.com/mapswipe/community-website/assets/109613542/bb97e4e0-6631-4d75-86c8-4ab981d69759)


![Image](https://github.com/mapswipe/community-website/assets/109613542/346f912e-a785-49df-852d-304d03d2a20b)
