### ISSUE TITLE
Home > Project Types - Do we use the icons shared or are we using illustrations?

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#97]
## Available Options

- Icon
- Illustration
- Icon with illustration

**Comment by kopitek8** [comment]
From the meeting on the 14th, let's go with icon with illustration

**Comment by jhenshall** [comment]
Yes, thanks @kopitek8. To add some context here, the thinking is that we build familiarity and association between project type name and icon - so these are always displayed together. For the home page, we also have an illustration that more visually shows the differences between the project types.

**Comment by jhenshall** [comment]
@kopitek8 sharing the icon SVGs here. Let me know if any other variations needed - png etc.? 

[MapSwipe icons - project types - SVG.zip](https://github.com/mapswipe/community-website/files/11789537/MapSwipe.icons.-.project.types.-.SVG.zip)
